export const DROP_PRODUCT = 'DROP_PRODUCT'
export const DROP_CATEGORY = 'DROP_CATEGORY'
export const DROP_ADDITIONAL_PRODUCT = 'DROP_ADDITIONAL_PRODUCT'
export const DROP_ADDITIONAL_CATEGORY = 'DROP_ADDITIONAL_CATEGORY'